export const Resources = {
    TROOPS_SELECTED: "Wybrano tylko wojsko",
    TROOPS_AND_TARGET_SELECTED: "Wojsko dojdzie __DAY__.__MONTH__ na __HOURS__:__MINUTES__<br/>Cel: __TARGET__ __PLAYER_INFO__",
    ERROR_FORUM_CONFIG_THREAD_ID: "forum_config.thread_id jest nieprawidłowy",
    ERROR_FORUM_CONFIG_SPOILER_NAME: "forum_config.spoiler_name jest nieprawidłowy",
    ERROR_FORUM_CONFIG_TTL: "forum_config.ttl jest nieprawidłowy",
    ERROR_FORUM_CONFIG_PAGE: "forum_config.page jest nieprawidłowy",
    ERROR_FORUM_CONFIG_THREAD_DOES_NOT_EXIST: "Wątek nie istnieje",
    ERROR_FORUM_CONFIG_SPOILER_NONE: "Spoiler o podanej nazwie nie istnieje",
    ERROR_FORUM_CONFIG_SPOILER_MULTIPLE: "Znaleziono więcej niż jeden spoiler o podanej nazwie",
    ERROR_FORUM_CONFIG_CODE_SNIPPET_NONE: "Wskazany spoiler nie zawiera konfiguracji",
    ERROR_FORUM_CONFIG_CODE_SNIPPET_MULTIPLE: "Wskazany spoiler zawiera więcej niż jedną konfigurację",
    ERROR_FORUM_CONFIG_CODE_SNIPPET_MALFORMED: "Wskazany spoiler nie zawiera konfiguracji w formacie JSON",
    ERROR_SCREEN_VILLAGE_OUT_OF_GROUP: "Wioska poza grupą. Przechodzę do następnej wioski z grupy",
    ERROR_SCREEN_REDIRECT: "Przechodzę do przeglądu placu",
    ERROR_SCREEN_NO_ACTION: "Na tym ekranie nie ma akcji do wykonania",
    ERROR_CONFIGURATION_MISSING: "Brak konfiguracji użytkownika",
    ERROR_CONFIGURATION_OPTION_UNKNOWN: "Skrypt zawiera nieznaną opcję",
    ERROR_TROOPS_NOT_ENOUGH: "Nie udało się wybrać wystarczającej liczby jednostek",
    ERROR_TROOPS_EMPTY_SELECTION: "Wybrane szablony nie pozwalają na wybór jednostek",
    ERROR_TROOPS_EMPTY_TEMPLATES: "Nie wybrano szablonów z wyborem jednostek",
    ERROR_POOL_EMPTY: "Obecne ustawienia nie definują żadnych celów",
    ERROR_POOL_EMPTY_SNOBS: "W puli wiosek pozostały wioski, leżące poza zasięgiem szlachciców",
    ERROR_POOL_EMPTY_BLOCKED_VILLAGES: "W puli wiosek pozostały wioski, które zostały niedawno wybrane",
    ERROR_POOL_EMPTY_BLOCKED_PLAYERS: "W puli wiosek pozostały wioski, które należą od ostatnio wybranych graczy",
    ERROR_POOL_EMPTY_NIGHT_BONUS: "W puli wiosek pozostały wioski, na które atak doszedłby w bonusie nocnym",
    ERROR_POOL_EMPTY_DATE_RANGES: "W puli wiosek pozostały wioski, na które atak doszedłby poza wybranymi przedziałami czasowymi"
};